- name: Install Drush
  sudo: yes
  apt: pkg=drush state=latest

- name: Check if Drupal is downloaded
  stat: path=/vagrant/drupal/install.php
  register: drupal_exists

- name: Download Drupal
  shell: drush dl drupal -y --destination=/vagrant --drupal-project-rename=drupal
  when: drupal_exists.stat.exists == false

- name: Create files directory
  file: path=/vagrant/drupal/sites/default/files state=directory

- name: Copy settings.php
  template: src=settings.j2 dest=/vagrant/drupal/sites/default/settings.php

- name: Check if Drupal is installed
  shell: mysql -uroot -p{{ mariadb.root_password }} -e 'SHOW DATABASES;' | grep {{ mariadb.database }}
  register: database_exists

- name: Install Drupal
  shell: drush si -y {{ drupal.install_profile }} --db-url='mysql://{{ mariadb.user }}:{{ mariadb.password }}@localhost/{{ mariadb.database }}' --site-name={{ drupal.site_name }} --account-name={{ drupal.account.username }} --account-pass={{ drupal.account.password }} chdir=/vagrant/drupal
  when: database_exists.rc == 0
